---
title: "QC"
date: "2026-05-25"
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
  root.dir = "D:/Documents/Workspace/GSE183276"
)
options(stringsAsFactors = FALSE)
gc()

setwd("D:/Documents/Workspace/GSE183276")
 getwd()
```


```{r setup, include=FALSE}
# Verify files available in the main project directory
list.files()

# Quick validation step (expected output: TRUE)
file.exists(
  "input/GSE183276_Kidney_Healthy-Injury_Cell_Atlas_scCv3_Counts_03282022.RDS"
)

# Load the count matrix object
counts <- readRDS(
  "input/GSE183276_Kidney_Healthy-Injury_Cell_Atlas_scCv3_Counts_03282022.RDS"
)

# Inspect object type
class(counts)
```


```{r cars}
inputDir  <- "input/"
outputDir <- "output/"
plotDir   <- "plots/"
```



```{r pressure, echo=FALSE}
library(Seurat)
library(SeuratDisk)
library(dplyr)
library(R.utils)  
library(ggplot2)
library(ggExtra)
library(RColorBrewer)
library(openxlsx)
library(dplyr)
library(scales)
library(HGNChelper)
library(dittoSeq)
library(harmony)
library(batchelor)
library(zellkonverter)
library(SingleCellExperiment)
search()
```


```{r}
data_GSE183276 <- readRDS(
  "input/GSE183276_Kidney_Healthy-Injury_Cell_Atlas_scCv3_Counts_03282022.RDS"
)
class(data_GSE183276)
dim(data_GSE183276)
```

# Generate a Seurat object from the count matrix
```{r}  
seurat_all <- CreateSeuratObject(counts = data_GSE183276, project = "GSE183276",min.cells = 3,min.features = 200)      
colnames(seurat_all@meta.data)
seurat_oi <- SplitObject(seurat_all, split.by = "orig.ident")
print(names(seurat_oi))
```

```{r}
id_map <- c(
  "AKI3010018" = "GSM5554468",
  "AKI3010034" = "GSM5554469",
  "AKI3010123" = "GSM5554470",
  "AKI3010125" = "GSM5554471",
  "AKI3210003" = "GSM5554472",
  "AKI3210034" = "GSM5554473",
  "AKI3210074" = "GSM5554474",
  "AKI3310005" = "GSM5554475",
  "AKI3310006" = "GSM5554476",
  "AKI3410050" = "GSM5554477",
  "AKI3410184" = "GSM5554478",
  "AKI3410187" = "GSM5554479",
  "DKD2710039" = "GSM5554480",
  "DKD2810051" = "GSM5554481",
  "DKD2910006a" = "GSM5554482",
  "DKD2910006b" = "GSM5554483",
  "DKD2910006c" = "GSM5554484",
  "DKD2910010" = "GSM5554485",
  "DKD2910011" = "GSM5554486",
  "DKD2910012" = "GSM5554487",
  "DKD2910013" = "GSM5554488",
  "DKD2910016" = "GSM5554489",
  "DKD3110001" = "GSM5554490",
  "DKD3110035" = "GSM5554491",
  "DKD3110040" = "GSM5554492",
  "DKD3110042" = "GSM5554493",
  "HCKD2910008" = "GSM5554494",
  "HCKD3110000" = "GSM5554495",
  "HCKD3110013" = "GSM5554496",
  "LDPRE0181" = "GSM5554497",
  "LDPRE0194" = "GSM5554498",
  "LDPRE027" = "GSM5554499",
  "LDPRE038" = "GSM5554500",
  "LDPRE0551" = "GSM5554501",
  "LDPRE0621" = "GSM5554502",
  "LDPRE19025" = "GSM5554503",
  "LDPRE1905" = "GSM5554504",
  "LDPRE98sc" = "GSM5554505",
  "LDSample1153EO1" = "GSM5554506",
  "LDSample1153EO2" = "GSM5554507",
  "LDSample1153EO3" = "GSM5554508",
  "LDSample1157EO1" = "GSM5554509",
  "LDSample1157EO2" = "GSM5554510",
  "LDSample1157EO3" = "GSM5554511",
  "LDSample1158EO1" = "GSM5554512",
  "LDSample1158EO2" = "GSM5554513",
  "LDSample1158EO3" = "GSM5554514",
  "LDSample1162EO1" = "GSM5554515",
  "LDSample1162EO2" = "GSM5554516"
)
```


# Map original sample IDs to corresponding GSM accessions
```{r}
mapped_names <- sapply(names(seurat_oi), function(x) {
  if(x %in% names(id_map)) return(id_map[[x]])
  else return(x)  # keep original if no mapping found
})

names(seurat_oi) <- mapped_names
seurat_list <- seurat_oi

# Check total number of Seurat objects
length(seurat_list)
# Display updated sample names
names(seurat_list)

# Save each sample as an individual Seurat object
for (s in names(seurat_list)) {
  saveRDS(
    seurat_list[[s]],
    file = file.path(inputDir, paste0(s, "_seurat.rds"))
  )
}
print(names(seurat_list))
```


# Import metadata table
```{r}
meta <- read.delim("input/GSE183276_Kidney_Healthy-Injury_Cell_Atlas_scCv3_Metadata_03282022.txt", header = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
meta
```


```{r}
# Load all sample-specific Seurat objects
rds_files <- list.files(inputDir, pattern = "_seurat\\.rds$", full.names = TRUE)
seurat_list <- lapply(rds_files, readRDS)

# Assign sample names
names(seurat_list) <- gsub("_seurat\\.rds$", "", basename(rds_files))
print(names(seurat_list))

# Identify duplicated gene names in count matrices
sapply(seurat_list, function(obj) {
  sum(duplicated(rownames(GetAssayData(obj, layer = "counts"))))
})
clean_seurat_list <- seurat_list
print(names(clean_seurat_list))
```

```{r}
# Combine all Seurat objects into a unified dataset
# Update orig.ident using GSM IDs
for (s in names(clean_seurat_list)) {
  clean_seurat_list[[s]]$orig.ident <- s  # s is GSM ID
}
seurat_combined <- merge(clean_seurat_list[[1]], y = clean_seurat_list[-1], add.cell.ids = names(clean_seurat_list))

# Inspect merged sample identities
unique(seurat_combined$orig.ident)

# Confirm all samples are included
setdiff(id_map, names(clean_seurat_list)) # should return 0

# Save merged Seurat object
saveRDS(seurat_combined, file =  paste0(outputDir,"01_GSE183276_seurat_combined.rds"))
```

```{r}
class(seurat_combined)            # 'Seurat'
Assays(seurat_combined)           # (RNA) assays available in the rds
DefaultAssay(seurat_combined)     # default/active (RNA) assay in the rds
dim(seurat_combined)              # 29447 genes/features x 109741 cells

```


```{r}
# Verify saved merged object
file.exists(paste0(outputDir, "01_GSE183276_seurat_combined.rds"))
```


```{r}
# Add biological condition labels for downstream QC visualization

table(seurat_combined$orig.ident)
gsm_ids <- unique(seurat_combined$orig.ident)

condition_map <- c(
  rep("AKI", 12),
  rep("DKD", 14),
  rep("HCKD", 3),
  rep("Healthy", 20)
)

names(condition_map) <- gsm_ids
```



```{r}
# Assign condition labels at the single-cell level
seurat_combined$Condition <- unname(condition_map[seurat_combined$orig.ident])

table(seurat_combined$Condition)
sum(is.na(seurat_combined$Condition))

# Inspect feature names
head(rownames(seurat_combined), 20)

# Calculate percentage of mitochondrial transcripts
seurat_combined[["percent.mt"]] <- PercentageFeatureSet(
  seurat_combined,
  pattern = "^MT-"
)

# Calculate percentage of ribosomal transcripts
seurat_combined[["percent.rb"]] <- PercentageFeatureSet(
  seurat_combined,
  pattern = "^RPL|^RPS"
)

# Review metadata columns
colnames(seurat_combined@meta.data)

# Summarize QC metrics
summary(seurat_combined$percent.mt)
summary(seurat_combined$percent.rb)
```

```{r}
#.................Perform QC..............#
# Define QC metrics to identify low-quality cells,
# empty droplets, stressed cells, and technical artifacts.

study_id <- "GSE183276"

# Add sample labels to metadata
seurat_combined <- AddMetaData(seurat_combined, metadata = seurat_combined$orig.ident, col.name = "Sample")

# Generate violin plots for QC metrics across samples
save_violin_plots_separate <- function(
    seurat_obj,
    plotDir,
    study_id,
    features = c("nCount_RNA", "nFeature_RNA", "percent.mt", "percent.rb")
) {
  

  # Create output directory if absent
  if (!dir.exists(plotDir)) 
  {
    dir.create(plotDir, recursive = TRUE)
  }
  
  meta <- seurat_obj@meta.data
  meta$sample <- as.factor(meta$orig.ident)
  
  for (feat in features) 
  {
    if (!feat %in% colnames(meta)) 
    {
      warning(paste("Skipping", feat, "- not found in metadata"))
      next
    }
  }
  
  
p <- ggplot(meta, aes(x = sample, y = .data[[feat]])) +
geom_violin(trim = TRUE, fill = "steelblue", alpha = 0.7) +
geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.6) +
labs(
title = feat,
x = "Sample",
y = feat
) +
theme_bw(base_size = 14) +
theme(
axis.text.x = element_text(angle = 45, hjust = 1),
plot.title = element_text(hjust = 0.5)
)
ggsave(
filename = file.path(
plotDir,
paste0(study_id, "_preQC_", feat, "_violin.png")
),
plot = p,
width = 16,
height = 9,
dpi = 400,
bg = "white"
)
}


save_violin_plots_separate(seurat_combined, plotDir, study_id)
```


```{r}
# Scatter plot of nCount vs nFeature with marginal histograms
density_scatter_plot <- function(seurat_obj, filename){
  df <- data.frame(
    log1p_nCount_RNA = log1p(seurat_obj$nCount_RNA),
    log1p_nFeature_RNA = log1p(seurat_obj$nFeature_RNA),
    Condition = seurat_obj$Condition
  )
  
  p <- ggplot(df, aes(x = log1p_nCount_RNA, y = log1p_nFeature_RNA, colour = Condition)) +
    geom_point(alpha = 0.3, size = 0.5) +
    theme_minimal() +
    theme(legend.position.inside = c(0.05, 0.95), legend.justification = c("left", "top"), legend.key.size = unit(0.5, 'cm')) +
    guides(color = guide_legend(override.aes = list(size = 5))) + # 'size' here controls the symbol size
    labs(x = "log1p(nCount_RNA)", y = "log1p(nFeature_RNA)")
  
  p <- ggMarginal(p, type = "histogram", fill = "skyblue", bins = 40)
  ggsave(
    filename,
    plot = p,
    width = 8,
    height = 10,
    dpi = 400,
    bg = "white"
  )
  
}

density_scatter_plot(
  seurat_filtered,
  file.path(
    plotDir,
    paste0(study_id, "_preQC_density-scatter.png")
  )
)
```



```{r}
# Detect and remove abnormal cells using Mahalanobis distance
fil_nCounts <- function(seurat_obj, threshold_mahalanobis){
  ncounts_data <- as.data.frame(seurat_obj@meta.data$nCount_RNA)
  colnames(ncounts_data) <- "nCount_RNA"
  
  mahalanobis_dist <- mahalanobis(
    x = ncounts_data,
    center = colMeans(ncounts_data),
    cov = cov(ncounts_data)
  )
  
  seurat_obj$mahal_dist_nCount <- mahalanobis_dist
  mahal.fil <- qchisq(threshold_mahalanobis, df = ncol(ncounts_data))
  message(paste0("Mahalanobis threshold: ", round(mahal.fil, 3)))
  
  cells_to_remove <- rownames(seurat_obj@meta.data)[seurat_obj$mahal_dist_nCount > mahal.fil]
  message(paste0("Removing ", length(cells_to_remove), " cells (outliers by nCount_RNA)"))
  
  return(subset(seurat_obj, cells = setdiff(colnames(seurat_obj), cells_to_remove)))
}
```



```{r}
# Filter cells with extremely low/high detected genes
# Low counts may represent empty droplets,
# while unusually high counts may indicate doublets
filter_nFeatures <- function(seurat_obj, min_feat, max_feat, ...) {
  return(subset(seurat_obj, subset = nFeature_RNA > min_feat & nFeature_RNA < max_feat))
}

# Remove cells with excessive mitochondrial RNA
filter_mt <- function(seurat_obj, max_mt) {
  return(subset(seurat_obj, subset = percent.mt < max_mt))
}

# Remove cells with elevated ribosomal RNA proportion
filter_rb <- function(seurat_obj, max_rb) {
  return(subset(seurat_obj, subset = percent.rb < max_rb))
}
```


```{r}
# Define QC cutoffs
study_id <- "GSE183276"
min_features <- 200 # Minimum genes detected per cell. <200 --> empty droplets/cause most noise
max_features <- 7000 # Upper limit to reduce probable doublets
max_percent_mt <- 15 # Threshold for mitochondrial transcript percentage
max_percent_rb <- 10 # Threshold for ribosomal transcript percentage. High rRNA --> low info content/technical bias
threshold_mahalanobis <- 0.95 # Mahalanobis cutoff for multivariate outlier removal

seurat_filtered <- filter_nFeatures(seurat_combined, min_features, max_features)

seurat_filtered <- filter_mt(seurat_filtered, max_percent_mt)

seurat_filtered <- fil_nCounts(seurat_filtered, threshold_mahalanobis)

seurat_filtered <- filter_rb(seurat_filtered,max_percent_rb)

# Cell counts before QC
df_pre_qc <- as.data.frame(table(seurat_combined$Sample))
colnames(df_pre_qc) <- c("Sample_ID", "Cells_Before_QC")

# Cell counts after QC
df_post_qc <- as.data.frame(table(seurat_filtered$Sample))
colnames(df_post_qc) <- c("Sample_ID", "Cells_After_QC")
```



```{r}
# Generate summary table comparing cell counts
# before and after quality filtering
final_qc_table <- merge(
  df_pre_qc,
  df_post_qc,
  by = "Sample_ID",
  all.x = TRUE
)

final_qc_table
total_cells_before_qc <- sum(final_qc_table$Cells_Before_QC, na.rm = TRUE)
total_cells_after_qc <- sum(final_qc_table$Cells_After_QC, na.rm = TRUE)

total_cells_before_qc
total_cells_after_qc
```



```{r}

#{r Save Summary Table}
qc_metrics_file <- file.path(outputDir, paste0(study_id, "_QC_metrics.csv"))
write.csv(final_qc_table, qc_metrics_file, row.names = FALSE)
cat("Saved QC summary table to:", qc_metrics_file, "\n")



study_id <- "GSE183276"

save_violin_plots_separate <- function(
    seurat_obj,
    plotDir,
    study_id,
    features = c("nCount_RNA", "nFeature_RNA", "percent.mt", "percent.rb")
) {
  
  # Ensure output directory exists
  if (!dir.exists(plotDir)) {
    dir.create(plotDir, recursive = TRUE)
  }
  
  meta <- seurat_obj@meta.data
  meta$sample <- as.factor(meta$orig.ident)
  
  for (feat in features) {
    
    if (!feat %in% colnames(meta)) {
      warning(paste("Skipping", feat, "- not found in metadata"))
      next
    }
    
    p <- ggplot(meta, aes(x = sample, y = .data[[feat]])) +
      geom_violin(trim = TRUE, fill = "steelblue", alpha = 0.7) +
      geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.6) +
      labs(
        title = feat,
        x = "Sample",
        y = feat
      ) +
      theme_bw(base_size = 14) +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5)
      )
    
    ggsave(
      filename = file.path(
        plotDir,
        paste0(study_id, "_postQC_", feat, "_violin.png")
      ),
      plot = p,
      width = 16,
      height = 9,
      dpi = 400,
      bg = "white"
    )
  }
}

save_violin_plots_separate(seurat_filtered, plotDir, study_id)
```


```{r}
# Scatter plot of nCount vs nFeature with marginal histograms
density_scatter_plot <- function(seurat_obj, filename){
  df <- data.frame(
    log1p_nCount_RNA = log1p(seurat_obj$nCount_RNA),
    log1p_nFeature_RNA = log1p(seurat_obj$nFeature_RNA),
    Condition = seurat_obj$Condition
  )
  
  p <- ggplot(df, aes(x = log1p_nCount_RNA, y = log1p_nFeature_RNA, colour = Condition)) +
    geom_point(alpha = 0.3, size = 0.5) +
    theme_minimal() +
    theme(legend.position.inside = c(0.05, 0.95), legend.justification = c("left", "top"), legend.key.size = unit(0.5, 'cm')) +
    guides(color = guide_legend(override.aes = list(size = 5))) + # 'size' here controls the symbol size
    labs(x = "log1p(nCount_RNA)", y = "log1p(nFeature_RNA)")
  
  p <- ggMarginal(p, type = "histogram", fill = "skyblue", bins = 40)
  ggsave(
    filename,
    plot = p,
    width = 8,
    height = 10,
    dpi = 400,
    bg = "white"
  )
  
}

density_scatter_plot(seurat_filtered, file.path(plotDir, paste0(study_id, "_postQC_density-scatter.png")))
```


```{r Keep only protein coding genes}
protein_coding_genes <- readLines("~/GSE183276/Protein_coding_genes.txt")

# Apply gene filtering prior to normalization
seurat_filtered <- subset(seurat_filtered, features = protein_coding_genes)

####  Explore Filtered Seurat Object after QC  ####
class(seurat_filtered)            # Seurat class
Assays(seurat_filtered)           # assays available in the rds
DefaultAssay(seurat_filtered)     # default/active assay in the rds
dim(seurat_filtered)              # 16442 genes/features x 5405 cells
```


```{r Save Filtered Seurat Object}
saveRDS(seurat_filtered, file = paste0(outputDir,"02_GSE183276_seurat_qc_filtered.rds"))
```


```{r Load again the Filtered Seurat Object}

seurat_filtered <- readRDS(file = paste0(outputDir, "02_GSE183276_seurat_qc_filtered.rds"))
```

```{r Standard workflow for normalization and scaling}
cat("Normalizing data using LogNormalize method (scale factor = 10,000)...\n")
seurat_processed <- NormalizeData(seurat_filtered,
                                 normalization.method = "LogNormalize")  

# Identify highly variable genes
seurat_processed <- FindVariableFeatures(seurat_processed, selection.method = "vst", nfeatures = 2500)
seurat_processed <- ScaleData(seurat_processed) 
seurat_processed <- RunPCA(seurat_processed, dims=1:100, npcs = 100)
```

```{r Custom colors for Condition in metadata}
custom_colors <- c("AKI"="purple3", "DKD"="darkorange3", "HCKD"="green4", "Healthy"="blue3")
```


```{r Elbow Plot}
# Determine variance contribution across principal components
stdev <- seurat_processed[["pca"]]@stdev
var_explained <- stdev^2 / sum(stdev^2)
cum_var <- cumsum(var_explained)
pca_var_df <- data.frame(
  PC = 1:length(stdev),
  Variance = var_explained,
  CumulativeVariance = cum_var
)
pca_var_df
num_PCs <- min(which(cum_var >= 0.95))  # first PC where cumulative variance >= 85%
num_PCs

elbow_plot <- ElbowPlot(seurat_processed, ndims = 100, reduction = 'pca')+
  labs(title = "PCA Elbow Plot for Dimensionality Selection")

ggsave(file.path(plotDir, paste0(study_id, "_ElbowPlot.png")),
       elbow_plot, width = 8, height = 6, bg = 'white')
```



```{r Total variance explained across the top 35 PCs}
# Calculate cumulative variance explained by top PCs
pca_stdev <- seurat_processed[["pca"]]@stdev
pca_var_explained <- (pca_stdev^2) / sum(pca_stdev^2) * 100
total_var<- sum(pca_var_explained[1:35])
cat("Total variance explained by top PCs:", round(total_var, 2), "%\n")
```


```{r Perform UMAP & Clustering on unintegrated data}
library(glue)
```


```{r Perform UMAP & Clustering on unintegrated data}
# Run UMAP on unintegrated data
seurat_processed <- RunUMAP(seurat_processed, dims = 1:35)
```


```{r Perform UMAP & Clustering on unintegrated data}
# Construct neighbor graph and identify clusters
seurat_processed <- FindNeighbors(seurat_processed, dims = 1:35, reduction = "pca", graph.name = "pca_nn")

seurat_processed <- FindClusters(seurat_processed, resolution = 0.8,graph.name = "pca_nn", cluster.name = "pca_clusters") 
n_clusters <- length(unique(seurat_processed$pca_clusters))
cat(glue("Clustering complete. Number of clusters: {n_clusters}\n"))  # 21 clusters found
```


```{r}
head(seurat_processed@meta.data, 3)
```



```{r Save Unintegrated Seurat Object}
# Save unintegrated Seurat object
saveRDS(seurat_processed, file = paste0(outputDir,"03_GSE183276_seurat_pca_umap.rds"))
#seurat_processed <- readRDS(file = paste0(outputDir, "03_GSE183276_seurat_pca_umap.rds"))

merged = JoinLayers(seurat_processed) 
sce <- as.SingleCellExperiment(merged, assay = "RNA")

dim(sce)
assayNames(sce)
reducedDimNames(sce)
head(colData(sce),2)

outputDir <- "~/GSE183276/demo/output/"
h5seurat_name <- "03_GSE183276_seurat_pca_umap.h5seurat"
h5ad_name <- "03_GSE183276_seurat_pca_umap.h5ad"

SaveH5Seurat(
  object = seurat_processed,
  filename = file.path(outputDir, h5seurat_name),
  overwrite = TRUE,
  version = "3"
)

writeH5AD(sce, file = paste0(outputDir, "03_GSE183276_seurat_pca_umap.h5ad"))
```


```{r}
system("git --version")
```



```{r Run Harmony & Perform Clustering on Harmony integrated data}
# Run Harmony integration and perform clustering
harmony_processed <- RunHarmony(seurat_processed, c("Sample"), plot_convergence = TRUE)

harmony_processed <- RunUMAP(harmony_processed, reduction = "harmony", dims = 1:50)

harmony_processed <- FindNeighbors(harmony_processed, reduction = "harmony", dims = 1:50, graph.name = "harmony_nn")

harmony_processed <- FindClusters(harmony_processed, graph.name = "harmony_nn", resolution = 0.8, group.name = "Harmony_clusters")
#found 22 clusters

saveRDS(harmony_processed, file = paste0(outputDir,"04_GSE183276_harmony_corrected.rds"))
#harmony_processed <- readRDS(file = paste0(outputDir, "04_GSE183276_harmony_corrected.rds"))

merged1 = JoinLayers(harmony_processed) 
sce_harmony <- as.SingleCellExperiment(merged1, assay = "RNA")

dim(sce_harmony)
assayNames(sce_harmony)
reducedDimNames(sce_harmony)
head(colData(sce_harmony),2)

outputDir <- "~/GSE183276/demo/output/"
h5seurat_name1 <- "04_GSE183276_harmony_corrected.h5seurat"
h5ad_name1 <- "04_GSE183276_harmony_corrected.h5ad"

SaveH5Seurat(
  object = harmony_processed,
  filename = file.path(outputDir, h5seurat_name1),
  overwrite = TRUE,
  version = "3"
)

writeH5AD(sce_harmony, file = paste0(outputDir,  "04_GSE183276_harmony_corrected.h5ad"))
```


```{r Dimention reduction plot on PCA}
# UMAP visualization before batch correction
p <- DimPlot(seurat_processed, reduction = "umap", group.by = "Sample") + ggtitle("Uncorrected") +  NoLegend()
  ggtitle("Uncorrected")
ggsave(filename = file.path(plotDir, "BENCHMARKING_GSE183276_RawPCA_sample.png"), width = 7, height = 6, dpi = 600)
p

p <-DimPlot(seurat_processed, reduction = "umap", group.by = "Condition") +
  ggtitle("Uncorrected")
ggsave(filename = file.path(plotDir, "BENCHMARKING_GSE183276_RawPCA_condition.png"), width = 8, height = 6, dpi = 600)
p
```


```{r}
#harmony_processed <- RunUMAP(harmony_processed, reduction = "harmony", dims = 1:30)
# UMAP visualization after Harmony integration
p2 <-DimPlot(harmony_processed, reduction = "umap", group.by = "Condition") + ggtitle("Harmony") 
ggsave(filename = file.path(plotDir, "BENCHMARKING_GSE183276_Harmony_condition.png"), width = 8, height = 6, dpi = 600)
p2

p <- DimPlot(harmony_processed, reduction = "umap", group.by = "Sample") + ggtitle("Harmony") +  NoLegend()
ggsave(filename = file.path(plotDir, "BENCHMARKING_GSE183276_Harmony_sample.png"), width = 7, height = 6, dpi = 600)
p

umap_hcoords <- Embeddings(harmony_processed, "umap")
write.csv(umap_hcoords, file="GSE183276_umap_coordinates.csv")
```


``` {r Combine Bar Plot}
library(ggplot2)
# Evaluate batch mixing across samples
compute_knn_batch_mixing <- function(
    seu,
    batch_var,
    reduction = "pca",
    dims = 1:50,
    k = 20
){
  
  
  if (!batch_var %in% colnames(seu@meta.data)) {
    stop(paste0("Metadata column '", batch_var, "' not found in seu@meta.data"))
  }
  
  if (!reduction %in% Reductions(seu)) {
    message("[INFO] PCA not found. Running Normalize → HVG → Scale → PCA")
    seu <- NormalizeData(seu, verbose = FALSE)
    seu <- FindVariableFeatures(seu, selection.method = "vst", nfeatures = 3000)
    seu <- ScaleData(seu, verbose = FALSE)
    seu <- RunPCA(seu, npcs = max(dims), verbose = FALSE)
  }
  
  emb <- Embeddings(seu, reduction = reduction)[, dims, drop = FALSE]
  nn  <- FNN::get.knn(emb, k = k)$nn.index
  labs <- seu@meta.data[[batch_var]]
  
  same <- sapply(seq_len(nrow(nn)), function(i){
    mean(labs[nn[i,]] == labs[i], na.rm = TRUE)
  })
  
  df <- data.frame(batch = labs, frac_same_batch = same)
  aggregate(frac_same_batch ~ batch, df, mean)
}

plot_knn_batch_mixing <- function(mix_df){
  ggplot(mix_df, aes(x = batch, y = frac_same_batch)) +
    geom_col(fill = "steelblue") +
    labs(
      title = "Batch Mixing",
      x = "Batch",
      y = "Mean same-batch fraction (higher = stronger batch effect)"
    ) +
    theme_minimal(base_size = 12)
}


batch_column <- "Sample"

mix_df <- compute_knn_batch_mixing(
  seu       = seurat_processed,             
  batch_var = batch_column,
  reduction = "pca",
  dims      = 1:50,
  k         = 20
)

mix_df_harmony <- compute_knn_batch_mixing(
  seu       = harmony_processed,
  batch_var = batch_column,
  reduction = "harmony",
  dims      = 1:50,
  k         = 20
)


mix_df_combined <- rbind(mix_df, mix_df_harmony)


mix_df_combined1 <- rbind(
  transform(mix_df, Status = "Before"),
  transform(mix_df_harmony, Status = "Harmony")
)
```


```{r Final Plot}
# Generate combined batch-correction comparison plot
batch_cor_plot <- ggplot(mix_df_combined1, aes(x = batch, y = frac_same_batch, fill = Status)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  labs(
    title = "Batch Mixing",
    x = "Samples",
    y = "Mean same-batch fraction (higher = stronger batch effect)"
  ) +
  scale_fill_manual(
    values = c(
      "Before" = "#00CED1",     # turquoise
      "Harmony" = "#9370DB"     # new purple shade (example 3rd color)
    )
  ) +
  theme_minimal(base_size = 15) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.title = element_blank(),
    plot.title = element_text(face = "bold", hjust = 0.5)
  )

batch_cor_plot

ggsave(filename = paste0(plotDir,"batch_correction_barplot_combined.png"), plot = batch_cor_plot, width = 23, height = 8, dpi = 300)
```

